# 文件上传目录
file:
  upload:
    url: D:\WorkSpace\Idea\ideaProjects\TestSpace

spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 3403761832@qq.com #这里填你的邮箱
    password: vbivsorckuhedbda #这里填你的授权码
    default-encoding: UTF-8


  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123456

  datasource:
    url: jdbc:mysql://localhost:3306/schema_01?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: demo_01

#    swagger2注释需要的...
  mvc:
    pathmatch:
        matching-strategy: ant-path-matcher
      # 设置最大的文件大小，不超过20MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

#  application:
#    name: springfox-swagger
#
#
#    # ===== 自定义swagger配置 ===== #
#  swagger:
#    enable: true
#    application-name: ${spring.application.name}
#    application-version: 1.0
#    application-description: springfox swagger 3.0整合Demo
#    try-host: http://localhost:${server.port}



server:
    port: 8082

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

